version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - release
init:
- ps: Set-Culture de-AT
build_script:
- ps: >-
    if ($env:APPVEYOR_RDP_PASSWORD)
    { 
        $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    }

    $env:vodamepnative = $true

    $env:vodamepversion = $env:APPVEYOR_BUILD_VERSION

    .\build.ps1 -Target Publish
test: off
artifacts:
- path: publish/dmc.zip
  name: dmc.zip
- path: publish/dms.zip
  name: dms.zip
- path: publish/dml.zip
  name: dml.zip
- path: publish/specifications.zip
  name: specifications.zip
- path: publish/Vodamep.*.nupkg  